Repository midea-lan/midea-local, pull requests merged in 2024-07, with the labels that each got.

#203 chore(main): release 1.2.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#211 chore(main): release 1.3.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#216 chore(main): release 1.3.1
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#218 chore(main): release 1.3.2
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#219 feat: rework auth flow - part 1
  library_test.py
  midealocal/cli.py
  midealocal/cloud.py
  tests/cloud_test.py
  tests/device_test.py
Labels: breaking change

#223 chore(main): release 2.0.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#226 chore(main): release 2.1.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#230 chore(main): release 2.1.1
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#234 chore(main): release 2.2.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#233 feat: segregate connect/auth/refresh/enable device duties
  midealocal/device.py
  midealocal/exceptions.py
  tests/device_test.py
Labels: breaking change

#243 chore: pr auto label
  .github/pr-labeler.yml
  .github/workflows/lint-pr.yml
  .github/workflows/pr.yml
Labels: misc

#246 chore: pr label token permission
  .github/workflows/lint-pr.yml
Labels: misc

#244 fix: `break` the loop when connected
  midealocal/device.py
Labels: bug

#248 feat(40): add `precision_halves` customization
  midealocal/devices/x40/__init__.py
  tests/devices/x40/__init__.py
  tests/devices/x40/device_x40_test.py
Labels: enhancement

#251 fix(ac): correct attributes based on msg type
  midealocal/devices/ac/__init__.py
Labels: bug

#245 fix(cloud): fix email obfuscation
  midealocal/cloud.py
Labels: bug

#254 chore: don't label release-please PRs
  .github/workflows/lint-pr.yml
Labels: misc

#225 feat(b8): first implementation
  midealocal/devices/b8/__init__.py
  midealocal/devices/b8/const.py
  midealocal/devices/b8/message.py
  midealocal/message.py
  tests/devices/b8/__init__.py
  tests/devices/b8/device_b8_test.py
Labels: enhancement

#253 chore(main): release 2.5.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending
