Repository midea-lan/midea-local, pull requests merged in 2024-09, with the labels that each got.

#284 fix: ed device power/lock return message set and body_type 0x15 parse
  midealocal/devices/ed/message.py
  midealocal/message.py
  tests/devices/ed/__init__.py
  tests/devices/ed/device_ed_test.py
  tests/devices/ed/message_ed_test.py
Labels: bug

#294 chore(message): improve debug log for send and received msg with attr…
  midealocal/message.py
Labels: misc

#292 chore(main): release 2.7.1
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#296 fix(device)!: socket exception and process rebuild
  midealocal/cli.py
  midealocal/device.py
  tests/cli_test.py
  tests/device_test.py
Labels: bug, breaking change

#297 chore(main): release 3.0.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#298 fix(device): prevent while true loop high cpu usage bug
  midealocal/device.py
Labels: bug

#300 chore(main): release 3.0.1
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#304 fix(device)!: rollback and improve send/recv socket exception
  midealocal/device.py
Labels: bug, breaking change

#305 chore(main): release 4.0.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending
