Repository midea-lan/midea-local, pull requests merged in 2024-08, with the labels that each got.

#255 fix: tank is always seen as full
  midealocal/devices/a1/__init__.py
Labels: bug

#231 feat: parse all the response items from MeijuCloud for get_device_inf
  midealocal/cloud.py
  tests/cloud_test.py
  tests/responses/meijucloud_get_device_info_alt.json
Labels: enhancement

#256 fix(cli): authenticate to get keys
  midealocal/cli.py
  tests/cli_test.py
Labels: bug

#257 chore(main): release 2.6.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#264 chore: funding
  .github/FUNDING.yml
Labels: misc

#265 fix(c3): silent typo
  midealocal/devices/c3/__init__.py
  midealocal/devices/c3/message.py
  tests/devices/c3/device_c3_test.py
  tests/devices/c3/message_c3_test.py
Labels: bug

#268 chore(cloud): mypy timeout typing
  midealocal/cloud.py
Labels: misc

#263 fix(cli): authenticate on discover v3 device
  midealocal/cli.py
  tests/cli_test.py
Labels: bug

#267 chore(main): release 2.6.1
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#266 fix(cli): discover must return a list
  midealocal/cli.py
  tests/cli_test.py
Labels: bug

#269 chore(main): release 2.6.2
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#270 fix(c3): silent level as string
  midealocal/devices/c3/__init__.py
  midealocal/devices/c3/message.py
  tests/devices/c3/device_c3_test.py
  tests/devices/c3/message_c3_test.py
Labels: bug

#271 fix: body_type default value is zero and not None
  midealocal/devices/e6/message.py
  midealocal/devices/ea/message.py
  midealocal/devices/ec/message.py
  midealocal/devices/ed/message.py
  midealocal/devices/fa/message.py
  midealocal/devices/fb/message.py
  midealocal/message.py
Labels: bug

#272 chore(main): release 2.6.3
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#278 feat(cli): use of preset account if cloud info missing
  midealocal/cli.py
  tests/cli_test.py
Labels: enhancement

#276 chore(device): improved authentication logs
  midealocal/device.py
Labels: misc

#281 fix(cloud): meiju cloud download_lua appliance_type error
  midealocal/cloud.py
Labels: bug

#279 chore(main): release 2.7.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending
