Repository midea-lan/midea-local, pull requests merged in 2024-10, with the labels that each got.

#307 fix(device)!: rollback and socket refresh_status
  midealocal/device.py
Labels: bug, breaking change

#309 chore(main): release 5.0.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#306 chore(cloud)!: rename MSmartHome
  .vscode/launch.json
  midealocal/cloud.py
  tests/cli_test.py
  tests/cloud_test.py
Labels: breaking change

#312 chore(main): release 6.0.0
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#317 fix: add missing body_type "163"
  midealocal/message.py
Labels: bug

#319 chore(main): release 6.0.1
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending

#323 chore(main): release 6.0.2
  CHANGELOG.md
  midealocal/version.py
Labels: autorelease: pending
